version: "3.8"

services:
  db:
    container_name: day09_db_ex02
    image: postgres:latest
    environment:
      POSTGRES_USER: day09_ex02
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_ex02
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
