version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: achraf
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local