version: "3.8"

services:
  db:
    container_name: day09_db
    image: postgres:latest
    environment:
      POSTGRES_USER: day09
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Change to your preferred email
      PGADMIN_DEFAULT_PASSWORD: admin # Change to a strong password
    ports:
      - "8080:80" # Exposes pgAdmin on localhost:8080
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local

