version: "3.8"

services:
  db:
    container_name: day09_db
    image: postgres:latest
    environment:
      POSTGRES_USER: day09
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
